<?php
global $language;
	
$language = array();
	
$language[0] = "";
$language[1] = "back";
$language[2] = "back";
$language[3] = "read more";
$language[4] = "";
$language[5] = "";
$language[6] = "to news archive";
$language[7] = "* obligatory";
$language[8] = "";
$language[9] = "send";
$language[10] = "more information";
$language[11] = "please select";
$language[12] = "print";
$language[13] = "next";
$language[14] = "";
$language[15] = "";
$language[16] = "";
$language[17] = "";
$language[18] = "";
$language[19] = "";
$language[20] = "name";
$language[21] = "date of birth";
$language[22] = "street";
$language[23] = "city";
$language[24] = "phone";
$language[25] = "mobile";
$language[26] = "mail";
$language[27] = "your message";
$language[28] = "";
$language[29] = "";
$language[30] = "";
$language[31] = "";
$language[32] = "";
$language[33] = "";
$language[34] = "";
	?>